<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_LocationUserRegionPrice</name>
   <tag></tag>
   <elementGuidId>9613da3e-f1de-47d8-a07a-99510b5857c4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom_sel_style ng-pristine ng-untouched ng-valid ng-animate ng-dirty-add ng-valid-parse-add ng-pristine-remove</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>selectMenu()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>menu.option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>option.value as option.name for option in options</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LocationUserRegionPrice Market</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;tablesaw-enhanced&quot;]/body[@class=&quot;page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-sidebar-closed&quot;]/div[@class=&quot;page-container ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;page-content-wrapper ng-scope&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;mt-element-list item-prd-menu admin-retailer-location item-prd-menu1-des item-prd-menu1-add&quot;]/div[@class=&quot;mt-list-head list-simple orange-font font-orange item-prd-header&quot;]/div[@class=&quot;list-head-title-container&quot;]/select[@class=&quot;form-control custom_sel_style ng-pristine ng-untouched ng-valid ng-animate ng-dirty-add ng-valid-parse-add ng-pristine-remove&quot;]</value>
   </webElementProperties>
</WebElementEntity>
